/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2019-05-30 04:51:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class aaa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>博客來-會員登入</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"博客來,會員登入\">\r\n");
      out.write("<meta name=\"description\" content=\"博客來-會員登入\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/css.css?201801\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://jci.book.com.tw/jss/jquery/jquery-1.6.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://jci.book.com.tw/jss/books/jqueryplugin/purl.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.placeholder.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/common.js\" ></script>\r\n");
      out.write("<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-TBZGS7');</script>\r\n");
      out.write("<script async='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("    var c = false;\r\n");
      out.write("    $('input, textarea').placeholder();\r\n");
      out.write("    $('#login_id').focus();\r\n");
      out.write("    $('.banner_btn').mouseover(function(e){ //banner\r\n");
      out.write("        var id = 'banner_' + $(this).attr('id');\r\n");
      out.write("        $('.banner_btn').removeClass('here');\r\n");
      out.write("        $(this).addClass('here');\r\n");
      out.write("        $('.banli').hide();\r\n");
      out.write("        $('#'+id).fadeIn();\r\n");
      out.write("    }).eq($('#bannerStart').val()).mouseover();\r\n");
      out.write("    $('#regen').click(function(e){   //更新驗證碼\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"/member/regen_captcha\",\r\n");
      out.write("            success: function(data, textStatus){\r\n");
      out.write("                var imgUrl = \"/member/captcha_login?\" + data;\r\n");
      out.write("                $('#captcha_img').empty().html('<img src=\"' + imgUrl + '\" width=\"160\" height=\"75\" />');\r\n");
      out.write("                $('#captcha').val('');\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus) {\r\n");
      out.write("                alert('系統忙碌中，請稍後再試');\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    });\r\n");
      out.write("    $('#captcha').keypress(function(e){  //captcha\r\n");
      out.write("        $('#captcha_warn').html('').hide();\r\n");
      out.write("        if (e.which == 13){\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            $('#books_login').click();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    $('#login_id').keypress(function(e){    //login id\r\n");
      out.write("        $('#id_warn').html('').hide();\r\n");
      out.write("        if (e.which == 13){\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            $('#books_login').click();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    $('#login_pswd').keypress(function(e){  //login pswd\r\n");
      out.write("        $('#pswd_warn').html('').hide();\r\n");
      out.write("        var s = String.fromCharCode(e.which);\r\n");
      out.write("        if ((s.toUpperCase() === s && s.toLowerCase() !== s && !e.shiftKey)||\r\n");
      out.write("                (s.toUpperCase() !== s && s.toLowerCase() === s && e.shiftKey)) { //caps is on\r\n");
      out.write("            $(\"#caps_warn\").show();\r\n");
      out.write("        }else if ((s.toLowerCase() === s && s.toUpperCase() !== s && !e.shiftKey)||\r\n");
      out.write("                (s.toLowerCase() !== s && s.toUpperCase() === s && e.shiftKey)) { //caps is off\r\n");
      out.write("            $(\"#caps_warn\").hide();\r\n");
      out.write("        }\r\n");
      out.write("        if (e.which == 13){\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            $('#books_login').click();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    $('#books_login').click(function(e){    //login\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        var loginId = $.trim($('#login_id').val());\r\n");
      out.write("        if (loginId == ''){    //驗證 login id\r\n");
      out.write("            $('#id_warn').html('請輸入帳號ID或email').show();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        var loginPswd = $.trim($('#login_pswd').val());\r\n");
      out.write("        if (loginPswd == ''){    //驗證 login pswd\r\n");
      out.write("            $('#pswd_warn').html('請輸入密碼 Password').show();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        var captcha = $.trim($('#captcha').val());\r\n");
      out.write("        if (captcha == ''){    //驗證 login pswd\r\n");
      out.write("            $('#captcha_warn').html('請輸入驗證碼').show();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        maskDivShow();\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"/member/login_do/\",\r\n");
      out.write("            data: {\r\n");
      out.write("                captcha: captcha,\r\n");
      out.write("                login_id: loginId,\r\n");
      out.write("                login_pswd: loginPswd\r\n");
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            type: 'POST',\r\n");
      out.write("            success: function(data, textStatus){\r\n");
      out.write("                var result = $.parseJSON(data);\r\n");
      out.write("                if (result.success){    //登入成功\r\n");
      out.write("                    if (result.code == 168){\r\n");
      out.write("                        location.href = \"https://cart.books.com.tw/member/login_2factors/B/?url=https%3A%2F%2Fwww.books.com.tw%2F%3Floc%3Dtw_website_001&content=\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                        if (result.code != 1){\r\n");
      out.write("                            $('#url').val(\"https://cart.books.com.tw/member/email_no_auth/\");\r\n");
      out.write("                        }\r\n");
      out.write("                        go();\r\n");
      out.write("                    }\r\n");
      out.write("                }else{  //登入失敗\r\n");
      out.write("                    maskDivHidden();\r\n");
      out.write("                    if (result.code == 1){  //驗證碼錯誤\r\n");
      out.write("                        $('#captcha').val('');\r\n");
      out.write("                        $('#regen').click();\r\n");
      out.write("                        $('#captcha_warn').html(result.msg).show();\r\n");
      out.write("                    } else if (result.code == 2){   //帳號密碼錯誤\r\n");
      out.write("                        $('#login_pswd').val('');\r\n");
      out.write("                        $('#captcha').val('');\r\n");
      out.write("                        $('#regen').click();\r\n");
      out.write("                        openPopDiv('wdialog');\r\n");
      out.write("                    } else if (result.code == 3){  //帳號密碼錯誤\r\n");
      out.write("                        c = true;\r\n");
      out.write("                        openPopDiv('wdialog');\r\n");
      out.write("                    } else if (result.code == 4){ //異常會員需修改密碼\r\n");
      out.write("                        $('#pswd_safety_text').html('<li>由於您已有一段時間未異動密碼，為維護個人帳戶的安全性，</li><li>需請您變更密碼，謝謝您的配合</li>');\r\n");
      out.write("                        $('#keep_password').hide();\r\n");
      out.write("                        $('#update_password2').hide();\r\n");
      out.write("                        $('#update_password1').show();\r\n");
      out.write("                        openPopDiv('pswd_safety');\r\n");
      out.write("                    } else if (result.code == 5){ //密碼最後異動日超過6個月\r\n");
      out.write("                        $('#pswd_safety_text').html('<li>您已超過六個月未異動密碼，建議您變更密碼，以維謢個人帳戶安全性!!</li>');\r\n");
      out.write("                        $('#update_password1').hide();\r\n");
      out.write("                        $('#update_password2').show();\r\n");
      out.write("                        $('#keep_password').show();\r\n");
      out.write("                        openPopDiv('pswd_safety');\r\n");
      out.write("                    } else if (result.code == 168){ //兩階段驗證登入\r\n");
      out.write("                        alert('系統忙碌中，請稍後再試');\r\n");
      out.write("                        location.reload();\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus) {\r\n");
      out.write("                alert('系統忙碌中，請稍後再試');\r\n");
      out.write("                maskDivHidden();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    var fbwin;\r\n");
      out.write("    $('#facebook_login').click(function(e){  //facebook login\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        maskDivShow();\r\n");
      out.write("        if (!fbwin || fbwin.closed !== false) {\r\n");
      out.write("            fbwin = window.open($('#fbUrl').val(), 'fb_login', 'left=500,top=200,width=500,height=300,toolbar=no,location=no,menubar=no,status=0');\r\n");
      out.write("        }\r\n");
      out.write("        fbwin.focus();\r\n");
      out.write("        var pollTimer = window.setInterval(function() {\r\n");
      out.write("            if (!fbwin || fbwin.closed !== false) { // !== is required for compatibility with Opera\r\n");
      out.write("                window.clearInterval(pollTimer);\r\n");
      out.write("                maskDivHidden();\r\n");
      out.write("            }\r\n");
      out.write("        }, 200);\r\n");
      out.write("    });\r\n");
      out.write("    $('#wdialog_close').click(function(e){   //login failed - close window\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        if (c){\r\n");
      out.write("            location.reload();\r\n");
      out.write("        }else{\r\n");
      out.write("            closePopDiv('wdialog');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    $('#retype').click(function(e){  //login failed - retype\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        if (c){\r\n");
      out.write("            location.reload();\r\n");
      out.write("        }else{\r\n");
      out.write("            closePopDiv('wdialog');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    $('#fbterm_close').click(function(e){   //fb使用說明 - 關閉視窗\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        closePopDiv('fbterm');\r\n");
      out.write("    });\r\n");
      out.write("    $('#fbterm_agreen').click(function(e){   //fb使用說明 - 同意\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        closePopDiv('fbterm');\r\n");
      out.write("        openPopDiv('link');\r\n");
      out.write("    });\r\n");
      out.write("    $('#fbterm_disagreen').click(function(e){   //fb使用說明 - 不同意\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        closePopDiv('fbterm');\r\n");
      out.write("    });\r\n");
      out.write("    $('#link_close').click(function(e){   //fb連結 - 關閉視窗\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        closePopDiv('link');\r\n");
      out.write("    });\r\n");
      out.write("    $('#link_id').keypress(function(e){ //link fb id\r\n");
      out.write("        $('#link_warn').html('').hide();\r\n");
      out.write("    });\r\n");
      out.write("    $('#link_pswd').keypress(function(e){  //link fb pswd\r\n");
      out.write("        $('#link_warn').html('').hide();\r\n");
      out.write("        var s = String.fromCharCode(e.which);\r\n");
      out.write("        if ((s.toUpperCase() === s && s.toLowerCase() !== s && !e.shiftKey)||\r\n");
      out.write("                (s.toUpperCase() !== s && s.toLowerCase() === s && e.shiftKey)) { //caps is on\r\n");
      out.write("            $(\"#link_warn\").html('大寫鎖定 (Caps Lock) 已啟用').show();\r\n");
      out.write("        }else if ((s.toLowerCase() === s && s.toUpperCase() !== s && !e.shiftKey)||\r\n");
      out.write("                (s.toLowerCase() !== s && s.toUpperCase() === s && e.shiftKey)) { //caps is off\r\n");
      out.write("            $(\"#link_warn\").html('').hide();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    $('#link_agreen').click(function(e){   //fb連結-同意\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        var linkId = $.trim($('#link_id').val());\r\n");
      out.write("        var linkPswd = $.trim($('#link_pswd').val());\r\n");
      out.write("        if (linkId == ''){    //驗證 link fb id\r\n");
      out.write("            $('#link_warn').html('請輸入帳號ID或email').show();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (linkPswd == ''){    //驗證 login pswd\r\n");
      out.write("            $('#link_warn').html('請輸入密碼 Password').show();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        $('#link_agreen').prop('disabled', true);\r\n");
      out.write("        $('#link_warn').html(\"連結中...請稍後...\").show();\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"/member/link_fb_do\",\r\n");
      out.write("            data: {\r\n");
      out.write("                link_id: linkId,\r\n");
      out.write("                link_pswd: linkPswd\r\n");
      out.write("            },\r\n");
      out.write("            type: 'POST',\r\n");
      out.write("            success: function(data, textStatus){\r\n");
      out.write("                var result = $.parseJSON(data);\r\n");
      out.write("                if (result.success){    //連結登入成功\r\n");
      out.write("                    go();\r\n");
      out.write("                }else{  //連結登入失敗\r\n");
      out.write("                    $('#link_agreen').prop('disabled', false);\r\n");
      out.write("                    $('#link_warn').html(result.msg).show();\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus) {\r\n");
      out.write("                alert('系統忙碌中，請稍後再試');\r\n");
      out.write("                $('#link_agreen').prop('disabled', false);\r\n");
      out.write("                $('#link_warn').html(\"\").show();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    $('#link_disagreen').click(function(e){   //fb連結-不同意\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        closePopDiv('link');\r\n");
      out.write("    });\r\n");
      out.write("    $('#pswd_close').click(function(e){   //密碼安全性提示訊息 - 關閉視窗\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        closePopDiv('pswd_safety');\r\n");
      out.write("    });\r\n");
      out.write("    $('#keep_password').click(function(e){ //密碼安全性 - 沿用舊密碼\r\n");
      out.write("        $('#keep_password').hide();\r\n");
      out.write("        $('#update_password1').hide();\r\n");
      out.write("        $('#update_password2').hide();\r\n");
      out.write("        var loginId = $.trim($('#login_id').val());\r\n");
      out.write("        var loginPswd = $.trim($('#login_pswd').val());\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"/member/keep_password\",\r\n");
      out.write("            data: {\r\n");
      out.write("                login_id: loginId,\r\n");
      out.write("                login_pswd: loginPswd\r\n");
      out.write("            },\r\n");
      out.write("            type: 'POST',\r\n");
      out.write("            success: function(data, textStatus){\r\n");
      out.write("                var result = $.parseJSON(data);\r\n");
      out.write("                if (result.success){    //更新會員檔成功\r\n");
      out.write("                    closePopDiv('pswd_safety');\r\n");
      out.write("                    $('#books_login').click();//完成登入的動作\r\n");
      out.write("                }else{\r\n");
      out.write("                    alert(result.msg);\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus) {\r\n");
      out.write("                alert('系統忙碌中，請稍後再試');\r\n");
      out.write("                maskDivHidden();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    $('#update_password1').click(function(e){ //密碼安全性 - 異常會員修改密碼\r\n");
      out.write("        $('#keep_password').hide();\r\n");
      out.write("        $('#update_password1').hide();\r\n");
      out.write("        $('#update_password2').hide();\r\n");
      out.write("        var loginId = $.trim($('#login_id').val());\r\n");
      out.write("        var url = $('#url').val();\r\n");
      out.write("        $().redirect('update_password', {'loginId': loginId,'unusual' : 'Y','back_url' :url}, 'POST');\r\n");
      out.write("    });\r\n");
      out.write("    $('#update_password2').click(function(e){ //密碼安全性 - 修改密碼\r\n");
      out.write("        $('#keep_password').hide();\r\n");
      out.write("        $('#update_password1').hide();\r\n");
      out.write("        $('#update_password2').hide();\r\n");
      out.write("        var loginId = $.trim($('#login_id').val());\r\n");
      out.write("        var url = $('#url').val();\r\n");
      out.write("        $().redirect('update_password', {'loginId': loginId,'unusual' : 'N','back_url' :url}, 'POST');\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("        });\r\n");
      out.write("function go(){\r\n");
      out.write("    // content analyze\r\n");
      out.write("    var content = $('#content').val();\r\n");
      out.write("    var ctParam = {};\r\n");
      out.write("    if (content.length !== 0){\r\n");
      out.write("        var ctAry = content.split(\";\");\r\n");
      out.write("        for(var key in ctAry) {\r\n");
      out.write("            var ctkey = ctAry[key].split('=');\r\n");
      out.write("            ctParam[ctkey[0]] = ctkey[1];\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    // url analyze\r\n");
      out.write("    var url = $('#url').val();\r\n");
      out.write("    var urlObj = $.url(url);\r\n");
      out.write("    var param = $.extend({}, urlObj.param(), ctParam);\r\n");
      out.write("    var domain = urlObj.attr('protocol') + '://' + urlObj.attr('host');\r\n");
      out.write("    var path = urlObj.attr('path');\r\n");
      out.write("    var method = 'GET';\r\n");
      out.write("    // post/get redirect\r\n");
      out.write("    if (url.indexOf('/shopping/cart.php') >= 0\r\n");
      out.write("            || url.indexOf('/shopping/promote_cart.php') >= 0\r\n");
      out.write("            || url.indexOf('/shopping/supplier_cart.php') >= 0){   //force POST\r\n");
      out.write("        method = 'POST';\r\n");
      out.write("    }\r\n");
      out.write("    $().redirect(domain + path, param, method);\r\n");
      out.write("}\r\n");
      out.write("function showFbTerm(){\r\n");
      out.write("    if ($('#fbterm_text').html() == \"\"){\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"/member/fb_login_service_term\",\r\n");
      out.write("            success: function(data, textStatus){\r\n");
      out.write("                $('#fbterm_text').html(data);\r\n");
      out.write("                openPopDiv('fbterm');\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus) {\r\n");
      out.write("                alert('系統忙碌中，請稍後再試');\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    }else{\r\n");
      out.write("        openPopDiv('fbterm');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  var googletag = googletag || {};\r\n");
      out.write("  googletag.cmd = googletag.cmd || [];\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  googletag.cmd.push(function() {\r\n");
      out.write("    googletag.defineSlot('/17812066/books_member_D_430x390_bot', [480, 320], 'div-gpt-ad-1515639533351-0').addService(googletag.pubads());\r\n");
      out.write("    googletag.pubads().enableSingleRequest();\r\n");
      out.write("    googletag.pubads().collapseEmptyDivs(true,true);\r\n");
      out.write("    googletag.enableServices();\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"color_public\">\r\n");
      out.write("<!--Header-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(\".search_set\").hover(function(){\r\n");
      out.write("        $(\".search_popup\").show();\r\n");
      out.write("    },function(){\r\n");
      out.write("        $(\".search_popup\").hide();\r\n");
      out.write("    });\r\n");
      out.write("    $(\".search_popup a\").click(function(){\r\n");
      out.write("        $(\"#cat\").val($(this).attr('cat'));\r\n");
      out.write("        $(\"#search_name\").text($(this).text());\r\n");
      out.write("        $(\".search_popup\").hide();\r\n");
      out.write("    });\r\n");
      out.write("    $(\"#search\" ).submit(function(e){\r\n");
      out.write("        if ($('#key').val() === ''){\r\n");
      out.write("            alert('請輸入關鍵字');\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--start pop win-->\r\n");
      out.write("<div class=\"newmember_pop newmember message_info clearfix\" id=\"pswd_safety\"  style=\"display: none;\">\r\n");
      out.write("      <div id=\"pswd_close\" class=\"close_pop\" title=\"關閉視窗\"><span>關閉視窗</span></div>\r\n");
      out.write("      <div class=\"bd_a\">\r\n");
      out.write("\t<h2 class=\"title_09\" title=\"提示訊息\">提示訊息</h2>\r\n");
      out.write("        <!--提示訊息-->\r\n");
      out.write("        <div class=\"set_cont\">\r\n");
      out.write("          <ul id=\"pswd_safety_text\">\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--End 提示訊息-->\r\n");
      out.write("        <div class=\"mod ft01 btnwrap clearfix\">\r\n");
      out.write("\t  <span><a href=\"#\" class=\"button02\" id=\"update_password1\">修改密碼</a></span>\r\n");
      out.write("          <span><a href=\"#\" class=\"button02\" id=\"update_password2\">修改密碼</a></span>\r\n");
      out.write("          <span><a href=\"#\" class=\"button03\" id=\"keep_password\">沿用舊密碼</a></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div><!--end pop win-->\r\n");
      out.write("<!--main_wrap-->\r\n");
      out.write("<div class=\"container_24 main_wrap clearfix\">\r\n");
      out.write("    <!--main_column( 20grid:790px )-->\r\n");
      out.write("    <div class=\"grid_20 push_2 newmember\">\r\n");
      out.write("        <div class=\"mod join_wrap clearfix\">\r\n");
      out.write("            <div class=\"box_1 grid_13 alpha\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"box_2 grid_7 omega\">\r\n");
      out.write("                <div class=\"content_wrap\">\r\n");
      out.write("                    <div class=\"bd_b\">\r\n");
      out.write("                        <h1 class=\"title_05\" title=\"會員登入\">會員登入</h1>\r\n");
      out.write("                        <div class=\"mod clearfix\">\r\n");
      out.write("                            <table class=\"table_c\">\r\n");
      out.write("                                <col width=\"50%\">\r\n");
      out.write("                                <col width=\"50%\">\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    <tr><td colspan=\"2\">\r\n");
      out.write("                                            <input type=\"text\" name=\"login_id\" id=\"login_id\" value=\"\" class=\"width01 input01\" required=\"required\" placeholder=\"帳號ID或email\" maxlength=\"50\" size=\"50\" tabindex=\"1\" autocorrect=\"off\" autocapitalize=\"none\">\r\n");
      out.write("                                            <p class=\"point msg\" id=\"id_warn\" style=\"display:none;\"></p>\r\n");
      out.write("                                        </td></tr>\r\n");
      out.write("                                    <tr><td colspan=\"2\">\r\n");
      out.write("                                            <input type=\"password\" name=\"login_pswd\" id=\"login_pswd\" class=\"width01 input01\" required=\"required\" placeholder=\"密碼 Password\" maxlength=\"12\" size=\"12\" tabindex=\"2\">\r\n");
      out.write("                                            <p class=\"point msg\" id=\"pswd_warn\" style=\"display:none;\"></p>\r\n");
      out.write("                                            <p class=\"point msg\" id=\"caps_warn\" style=\"display:none;\">大寫鎖定 (Caps Lock) 已啟用</p>\r\n");
      out.write("                                            <input type=\"hidden\" name=\"url\" id=\"url\" value=\"https://www.books.com.tw/?loc=tw_website_001\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"content\" id=\"content\" value=\"\">\r\n");
      out.write("                                        </td></tr>\r\n");
      out.write("                                    <tr><td colspan=\"2\">\r\n");
      out.write("                                            <input type=\"text\" name=\"captcha\" id=\"captcha\" class=\"width01 input01\" required=\"required\" placeholder=\"請輸入驗證碼（不分大小寫）\" maxlength=\"4\" size=\"6\" autocomplete=\"off\" tabindex=\"3\">\r\n");
      out.write("                                            <p class=\"point msg\" id=\"captcha_warn\" style=\"display:none;\"></p>\r\n");
      out.write("                                    </td></tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <div id=\"captcha_img\"><img src=\"/member/captcha_login?82a7002dd7c0c6033118c0d0d1db10ce\" width=\"160\" height=\"75\"></div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td style=\"text-align:center;\"><p><a href=\"javascript:;\" id=\"regen\">更新驗證碼</a></p></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr><td colspan=\"2\"><button id=\"books_login\" class=\"button04\" tabindex=\"4\">登入</button></td></tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mod clearfix\">\r\n");
      out.write("                            <ul class=\"member_m03\">\r\n");
      out.write("                                <li class=\"li_left\"><a href=\"/member/forgot\">忘記帳號密碼</a></li>\r\n");
      out.write("                                <li class=\"li_right\">還不是會員? <a href=\"/member/join_step1\" target=\"_blank\">加入會員</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mod join_btn\">\r\n");
      out.write("                            <h3>您也可以用現有帳號， 快速登入</h3>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"javascript:;\" title=\"Facebook登入\" id=\"facebook_login\" class=\"join_fb\">Facebook登入</a>\r\n");
      out.write("                                    <input type=\"hidden\" id=\"fbUrl\" value=\"https://www.facebook.com/v3.2/dialog/oauth?client_id=210743125726405&scope=email,public_profile,user_birthday&redirect_uri=https%3A%2F%2Fcart.books.com.tw%2Fmember%2Ffb_login_do&display=popup\" />\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("<!--                <div>\r\n");
      out.write("                    <div id=\"twcaseal\" class=\"small3\" style=\"height:100px; margin:10px auto 0; width: 113px;\"><img src='/image/twcaseal_small3.jpg'/></div>\r\n");
      out.write("                    <script type=\"text/javascript\" src=\"//ssllogo.twca.com.tw/twcaseal2_v3.js\" charset=\"utf-8\"></script>\r\n");
      out.write("                </div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!--end main_column-->\r\n");
      out.write("    <!--right_column( 2grid:70px )-->\r\n");
      out.write("    <div class=\"grid_2 push_2\">&nbsp;</div><!--end right_column-->\r\n");
      out.write("    <!--left_column( 2grid:70px )-->\r\n");
      out.write("    <div class=\"grid_2 pull_22\">&nbsp;</div><!--end left_column-->\r\n");
      out.write("\r\n");
      out.write("</div><!--End main_wrap-->\r\n");
      out.write("<!--footer-->\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
